### ISSUE TITLE
Seems like the reactor is not working on corporate proxy 

### ISSUE THREAD

**Issue by devopsfactory-in** [adobe/reactor-sdk-javascript#21]
Hi Team,

While using the reactor javascript sdk over the corporate proxy we are getting the following error.

{ FetchError: request to https://reactor.adobe.io/properties/3333/extensions failed, reason: getaddrinfo ENOTFOUND reactor.adobe.io reactor.adobe.io:443
13:42:33     at ClientRequest.<anonymous> (/home/node_modules/node-fetch/lib/index.js:1444:11)
13:42:33     at ClientRequest.emit (events.js:198:13)
13:42:33     at TLSSocket.socketErrorListener (_http_client.js:392:9)
13:42:33     at TLSSocket.emit (events.js:198:13)
13:42:33     at emitErrorNT (internal/streams/destroy.js:91:8)
13:42:33     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
13:42:33     at process._tickCallback (internal/process/next_tick.js:63:19)
13:42:33   message:
13:42:33    'request to https://reactor.adobe.io/properties/3333/extensions failed, reason: getaddrinfo ENOTFOUND reactor.adobe.io reactor.adobe.io:443',
13:42:33   type: 'system',
13:42:33   errno: 'ENOTFOUND',
13:42:33   code: 'ENOTFOUND' }

Seems like the proxying is not supported by node-fetch  https://github.com/bitinn/node-fetch/issues/79
https://github.com/bitinn/node-fetch/issues/81

**Comment by thebenrob** [comment]
From this output it looks like your corporate network is blocking requests to reactor.adobe.io entirely.  This does work on other private VPNs that we've tested on, thus it shouldn't be related to node-fetch.  Can you verify that you can actually reach reactor.adobe.io on your corporate network by curl or ping and let us know how that works?

**Comment by thebenrob** [comment]
Please reopen the issue if needed.
