### ISSUE TITLE
copy(userData.imsAccessToken) is not working on new Launch URL

### ISSUE THREAD

**Issue by devopsfactory-in** [adobe/reactor-sdk-javascript#53]
Hi Team,

The 'userData' object is not defined on the newly migrated Launch URL.

https://experience.adobe.com/#/@<orgname>/launch/companies/

Could you please provide a solution here

**Comment by jeffchasin** [comment]
`window.adobeIMS.getAccessToken()` should do the trick.

(h/t to Mr. Highland for the solution)

**Comment by devopsfactory-in** [comment]
Thanks for the update
