### ISSUE TITLE
[Question] 'http://localhost:3000' has been blocked by CORS policy

### ISSUE THREAD

**Issue by stk26kakarla** [adobe/reactor-sdk-javascript#56]
The request URL I am accessing works with node-fetch and Postman. And when I try the same URL and Access Token the SDK throws the error: 
Access to fetch at 'https://reactor.adobe.io/companies' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field cache-control is not allowed by Access-Control-Allow-Headers in preflight response.

I am sure that there are Header differences, but how can I add the headers in this SDK?
Is there anyway to not block the localhost environment?

**Comment by thebenrob** [comment]
If you're running a local server, then you'll have to fix the CORS headers on that local server to fix this.  You may want to check out a couple links to help you with this:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
- https://auth0.com/blog/cors-tutorial-a-guide-to-cross-origin-resource-sharing/
If you just need this for local development on your machine, there are browser extensions that let you do this also.
