### ISSUE TITLE
404 error when accessing "https://unpkg.com/@adobe/reactor-sdk/dist/reactor-sdk.min.js"

### ISSUE THREAD

**Issue by stewartschillingsdi** [adobe/reactor-sdk-javascript#58]
There is nothing hosted at "https://unpkg.com/@adobe/reactor-sdk/dist/reactor-sdk.min.js"

**Comment by thebenrob** [comment]
We actually found this out ourselves a few days ago.  Apparently the last time we built it, we used the wrong name.  We'll do a new build to fix it, but in the meantime, you can find it here: https://unpkg.com/@adobe/reactor-sdk@1.0.6/dist/reactor.min.js

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL
