### ISSUE TITLE
filter[published] not working for listRevisionsForRule

### ISSUE THREAD

**Issue by uptimal-julia-pujol** [adobe/reactor-sdk-javascript#64]
### Expected Behaviour
**filter[published]: 'EQ true'** should return the rule version that it's currently published. This filter is listed as a proper filter for this method in the API docs: https://developer.adobelaunch.com/api/reference/1.0/rules/list/

### Actual Behaviour
It does not filter. Probably there is a problem with the booleans.

#### Sample Code that illustrates the problem
  let ruleRevisionsList =
    await launchApiClient
      .listRevisionsForRule(rule.data.id, {
        'filter[published]': 'EQ true'
      })

**Comment by uptimal-julia-pujol** [comment]
In fact, it doesn't accept any kind of parameter, not even the pagination ones.

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL as Bug

**Comment by uptimal-julia-pujol** [comment]
Glad to see this live, thanks.
