### ISSUE TITLE
No way to provide x-gw-ims-org-id header

### ISSUE THREAD

**Issue by thebenrob** [adobe/reactor-sdk-javascript#66]
### Expected Behaviour

I need a way to provide the x-gw-ims-org-id header when using the SDK.

### Actual Behaviour

There is not currently a mechanism to provide this, with the recent change to enforce usage of this header in the API, I can no longer use the SDK.

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL

**Comment by brenthosie** [comment]
Interestingly, I only have run into this with an expired token. I have been able to get results from the API.
