### ISSUE TITLE
Provide instructions in the README to use jwt-auth to grab an access token for CI/CD or Back End Uses

### ISSUE THREAD

**Issue by brenthosie** [adobe/reactor-sdk-javascript#69]
<![](--- STOP) Before you open an issue please search this repository's issues to see if it has already been reported. This helps reduce duplicate issues from being created. -->

Helpful? https://developer.adobelaunch.com/api/guides/access_tokens/

1. https://github.com/adobe/jwt-auth
2. Upate README instructions

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL as Task
